FROM node:14
# test secret - AWS key
ENV AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
ENV AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
WORKDIR /app
COPY package*.json ./
RUN npm install
RUN npm install -g nodemon
RUN npm install fetch
COPY . .
EXPOSE 3000
CMD ["npm", "run", "start:concurrent"]