name: SCA + Secrets Scan

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  sca-secrets-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run SCA + secrets scan
        env:
          BACKEND_API_URL: "https://skimpily-talcum-tall.ngrok-free.dev"
          BACKEND_API_TOKEN: ${{ secrets.BACKEND_API_TOKEN }}
        run: |
          docker pull public.ecr.aws/e9l9t5a0/sca-secrets-public:latest
          docker run --rm \
            -v "${{ github.workspace }}":/workspace \
            -e BACKEND_API_URL \
            -e BACKEND_API_TOKEN \
            public.ecr.aws/e9l9t5a0/sca-secrets-public:latest \
            --input /workspace --scans sca,secrets --fail-on HIGH